version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../devops/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    volumes:
      - ../frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ../backend
      dockerfile: ../devops/Dockerfile.backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=hotel_management
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=dev_secret_key
      - JWT_EXPIRATION=24h
      - API_PORT=3001
    volumes:
      - ../backend:/app
      - /app/node_modules

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: